#!/bin/bash
# Compile the programs

javac J2V.java

for filename in testFiles/*.java; do
	echo "Creating vapor for "$filename""
	java J2V < $filename > testVapor/$(basename $filename .java).vapor
	echo ""
done

make clean
