#!/bin/bash
# Compile the programs
if [[ $* == *--make* ]]; then
	make hw4
fi

if [[ $* == *--out* ]]; then
	sh create_output_VM2M
fi

rm tmp.vapor tmp.out 2> /dev/null

for filename in testVaporM/*.vapor; do
	echo "Testing file: "$filename""
	java -cp ".:vapor-parser.jar" VM2M < $filename > tmp.s
	java -jar mars.jar nc tmp.s > tmp.out
	diff -y tmp.out testVaporMOutput/$(basename $filename .vaporm).out
	rm tmp.s tmp.out 2> /dev/null
	echo ""
done

if [[ $* == *--make* ]]; then
	make clean
fi
