#!/bin/bash
# Compile the programs
if [[ $* == *--make* ]]; then
	make
fi

for filename in testFiles/*.java; do
	echo "Testing file: "$filename""
	diff <($(java Typecheck << $filename)) <($(cat typeCheck/$(basename $filename .java).out))
	echo ""
done
